### ISSUE TITLE
Updating Documentation

### ISSUE THREAD

**Issue by lccodes** [jdahmubed/oicmsg_justin#1]
https://github.com/jdahmubed/oicmsg_justin/blob/feafcd54b25c4cd5588ea793b311731204780376/java-jwt/lib/src/main/java/com/auth0/jwt/JWT.java#L27

Can you update the comments to align with your proposed API? It's hard to tell how it's working with semi-accurate comments.

**Comment by jdahmubed** [comment]
Done.
