### ISSUE TITLE
Docs Inconsistency

### ISSUE THREAD

**Issue by lccodes** [jdahmubed/oicmsg_justin#2]
https://github.com/jdahmubed/oicmsg_justin/blob/feafcd54b25c4cd5588ea793b311731204780376/java-jwt/lib/src/main/java/com/auth0/jwt/JWT.java#L69

Can you rewrite these to not just copy verifier functionality over here, but also integrate the comments + methods more seamlessly into JWT? For example, these methods should look native to JWT rather than ported over from and still referencing the class formerly known as JWTVerifier.

**Comment by jdahmubed** [comment]
Done.
