### ISSUE TITLE
Having absolute date values in a test is bad

### ISSUE THREAD

**Issue by rohe** [jdahmubed/oicmsg_justin#3]
https://github.com/jdahmubed/oicmsg_justin/blob/ea93ec125b63f0917f32dc4bc08d802b09d23991/java-jwt/lib/src/test/java/com/auth0/jwt/GoogleJwtCreatorTest.java#L35

You have to set the exp date dynamically to be X minutes/hours/days/months in advance.

Would be nice to have a test where the exp point in time has passed.

**Comment by jdahmubed** [comment]
I have fixed this with the latest changes.
