### ISSUE TITLE
Checking 'sub' doesn't make sense to me

### ISSUE THREAD

**Issue by rohe** [jdahmubed/oicmsg_justin#4]
https://github.com/jdahmubed/oicmsg_justin/blob/ea93ec125b63f0917f32dc4bc08d802b09d23991/java-jwt/lib/src/test/java/com/auth0/jwt/GoogleJwtCreatorTest.java#L155

Commented on this to Anju too.
'sub' is what it is. It's the subject identifier of the entity that authenticated. 
You can't know what it should be.

**Comment by jdahmubed** [comment]
Ok interesting.  I'll remove it as a param from createVerifier().
