### ISSUE TITLE
Non standard claim should not lead to an exception

### ISSUE THREAD

**Issue by rohe** [jdahmubed/oicmsg_justin#5]
https://github.com/jdahmubed/oicmsg_justin/blob/ea93ec125b63f0917f32dc4bc08d802b09d23991/java-jwt/lib/src/test/java/com/auth0/jwt/GoogleJwtCreatorTest.java#L197

Non standard claims must be allowed. They can't just be checked for validity.

**Comment by jdahmubed** [comment]
Hi Roland.  I am allowing them, and I'm not verifying them.  Where do you see otherwise?

**Comment by rohe** [comment]
But the test description says it's suposed to throw an exception or am I misreading ?

**Comment by jdahmubed** [comment]
I think you might be misreading.  I'm not expecting an exception in the test.

**Comment by rohe** [comment]
So why does it say thrown.expect(InvalidClaimException.class); on line 196 is that not telling the test harnes that an exception should be expected ?

**Comment by jdahmubed** [comment]
You mean line 176?  That's inside of the testGoogleJwtCreatorInvalidAudience test.
