### ISSUE TITLE
As for Anju no tests on access to the message claims 

### ISSUE THREAD

**Issue by rohe** [jdahmubed/oicmsg_justin#6]
Or are they somewhere where I can't find them ?

**Comment by jdahmubed** [comment]
Hi Roland.  This is for Anju, right?  If so, I can pass on the message.

**Comment by rohe** [comment]
No, I can't see how someone using this library can get access to the message/JWT claims.
After the JWT has been verified and decoded.
You may have a method for that but it's not obvious from the tests.

**Comment by jdahmubed** [comment]
Once I get the DecodedJwt object, I can call getClaims() on it which will return me a hashmap for the claims.  I didn't think that was necessary to call for testing purposes.  Please correct me if I'm wrong.

**Comment by rohe** [comment]
Since that is the way people will access the information in a JWT, yes I think it's vital to test it.

**Comment by jdahmubed** [comment]
Ok I will add that check for all tests then.
